version: '3'

services:
  server:
    build: .
    restart: always
    depends_on:
      - database
    ports:
      - 7777:7777
    volumes:
      - ./server.js:/srv/server.js
      - ./public:/srv/public
      - ./scripts:/srv/scripts
      - ./node_modules:/srv/node_modules

  database:
    image: mongo:4
    volumes:
      - mongo:/data/db

volumes:
  mongo:
