version: '3'

services:
  server:
    build: .
    restart: always
    depends_on:
      - database
    ports:
      - 7777:7777

  database:
    image: mongo:4
    restart: always
    volumes:
      - mongo:/data/db

volumes:
  mongo:
