version: '3'

services:
  server:
    build: .
    restart: always
    depends_on:
      - mongo
    ports:
      - 7777:7777
    volumes:
      - ./:/home/cisl/server

  mongo:
    image: mongo:4
    restart: always
    volumes:
      - mongo:/data/db

volumes:
  mongo:
